const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const plantSchema = new Schema({
  id: { type: Number, unique: true, required: true },
  common_name: { type: String, required: true },
  scientific_name: [String],
  other_name: [String],
  family: String,
  origin: String,
  type: String,
  dimensions: {
    type: String,
    min_value: Number,
    max_value: Number,
    unit: String,
  },
  cycle: String,
  watering: String,
  depth_water_requirement: {
    unit: String,
    value: Number,
  },
  volume_water_requirement: {
    unit: String,
    value: Number,
  },
  watering_period: String,
  watering_general_benchmark: {
    value: String,
    unit: String,
  },
  plant_anatomy: {
    bark: String,
    leaves: String,
  },
  sunlight: [String],
  pruning_month: [String],
  pruning_count: {
    amount: Number,
    interval: String,
  },
  seeds: Number,
  attracts: [String],
  propagation: [String],
  hardiness: {
    min: String,
    max: String,
  },
  hardiness_location: {
    full_url: String,
    full_iframe: String,
  },
  flowers: Boolean,
  flowering_season: String,
  color: String,
  soil: [String],
  pest_susceptibility: String,
  cones: Boolean,
  fruits: Boolean,
  edible_fruit: Boolean,
  fruit_color: String,
  fruiting_season: String,
  harvest_season: String,
  harvest_method: String,
  leaf: Boolean,
  leaf_color: [String],
  edible_leaf: Boolean,
  growth_rate: String,
  maintenance: String,
  medicinal: Boolean,
  poisonous_to_humans: Boolean,
  poisonous_to_pets: Boolean,
  drought_tolerant: Boolean,
  salt_tolerant: Boolean,
  thorny: Boolean,
  invasive: Boolean,
  rare: Boolean,
  rare_level: String,
  tropical: Boolean,
  cuisine: Boolean,
  indoor: Boolean,
  care_level: String,
  description: String,
  default_image: {
    image_id: Number,
    license: Number,
    license_name: String,
    license_url: String,
    original_url: String,
    regular_url: String,
    medium_url: String,
    small_url: String,
    thumbnail: String,
  },
});

const GardenPlant = mongoose.model('GardenPlant', plantSchema);

module.exports = GardenPlant;
