import Head from "next/head";
import { useRouter } from "next/router";
import Button from "@mui/material/Button";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Garden App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Landing Page</h1>
        <Button variant="contained" color="primary">
          Contained
        </Button>
      </div>
    </>
  );
}
