import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import makePerenualAPIRequest from '../api/explore';
import PlantSearch from '@/components/PlantSearch';
import Navbar from "../../components/Navbar";


export const getStaticProps = async () => {
  const result = await makePerenualAPIRequest();
  return { props: {result}}
}
  export default function Explore({result}) {
    // const [result, setResult] = useState([]);
  
    // useEffect(() => {
    //   makePerenualAPIRequest().then((responseResult) => {
    //     setResult(responseResult);
    //   });
    // }, []);
    // console.log(result.data);
  
    return (
      <>
        <Head>
          <title>Garden App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Navbar />
          <h1>Explore</h1>
          <PlantSearch />
          {Array.isArray(result.data) && result.data.length > 0 ? (
            result.data.map((data) => (
              <div key={data.id}>
                <h2>{data.common_name}</h2>
                <p>{data.scientific_name}</p>
                {/* Add more data fields as needed */}
                {data.image_url ? (
                  <div>
                    <img src={data.image_url} alt="Default Image" />
                  </div>
                ) : (
                  <p>No default image available</p>
                )}
              </div>
            ))
          ) : (
            <p>No data available</p>
          )}
        </main>
      </>
    );
  };

